### ISSUE TITLE
修改main.py里的SC_KEY -> SCKEY

### ISSUE THREAD

**Issue by t0hka1** [HaleyCH/HDU_AUTO_BOOK-public#1]

**Comment by t0hka1** [comment]
重新看了下，应该是改main.py里的SC_KEY  -> SCKEY

**Comment by HaleyCH** [comment]
以修正

**Comment by ZRui-C** [comment]
已修正

**Comment by t0hka1** [comment]
> 已修正

这个issue的标题有误（
根据你的Action配置文件来看，其实README不用改，只要改main.py里的这个
![2023-02-05_21-12](https://user-images.githubusercontent.com/88968902/216821015-c5d43ed2-8d27-4f47-aefc-49e655d992c6.png)

**Comment by ZRui-C** [comment]
已修正（
