### ISSUE TITLE
不好意思打扰到您

### ISSUE THREAD

**Issue by RemainsOFtheDay** [HaleyCH/HDU_AUTO_BOOK-public#15]
作者大大您好，我按照文中指示的步骤做了，但还是完成不了预约。。。可以加您联系方式问一下怎么用吗，或者您能出个更傻瓜式的简短视频教程吗，我会有偿答复您的:)

**Comment by ZRui-C** [comment]
不好意思最近在忙没及时回应，原先V2版代码确实有一些问题，在最新版V2代码中已得到修复。如果是在配置环境时出现任何问题，请附上操作步骤与遇到的问题，如果可以，最好把GitHub Action的输出也一并附上

**Comment by ZRui-C** [comment]
已添加视频教程

**Comment by RemainsOFtheDay** [comment]
谢谢您！太感谢了💖
