### ISSUE TITLE
更新后无法预约 autobook为0s

### ISSUE THREAD

**Issue by Edwardyooooooo** [HaleyCH/HDU_AUTO_BOOK-public#4]
![image](https://user-images.githubusercontent.com/87703911/226932809-cf4ccb50-e128-4038-aeb3-6a14a90d0763.png)
更新后的版本，无法预约，之前版本预约已经有座的会在autobook报错，现版本无论座位是否被其他人预约，action后没有效果

**Comment by ZRui-C** [comment]
嘶，GitHub上用的是UTC时间，我本地是UTC+8，差了8小时，等我改改（（（

**Comment by ZRui-C** [comment]
等我今晚9点多验证完再改

**Comment by ZRui-C** [comment]
已更新
