### ISSUE TITLE
二楼阅览室预约

### ISSUE THREAD

**Issue by DlwlrmaL** [HaleyCH/HDU_AUTO_BOOK-public#6]
大佬能添加一个预约二楼阅览室的功能吗，谢谢

**Comment by ZRui-C** [comment]
阅览室因为座位整理的比较麻烦我就没整理，需要慢慢抓包。但其实自定义座位就是针对阅览室的。

btw，我没看到二楼有阅览室啊🤔
![image](https://user-images.githubusercontent.com/29998135/233527227-9995288c-d665-4895-8d5d-acf96fc405e7.png)

**Comment by ZRui-C** [comment]
电子阅览室吗🤔

**Comment by DlwlrmaL** [comment]
对，电子阅览室最近才上线预约系统，而且座位好难抢

**Comment by ZRui-C** [comment]
今晚抓个包

**Comment by DlwlrmaL** [comment]
谢谢

**Comment by ZRui-C** [comment]
已完成修改

**Comment by DlwlrmaL** [comment]
谢谢
